/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_drcom_drpalm_Tool_service_DrPushServiceJni */

#ifndef _Included_com_drcom_drpalm_Tool_service_DrPushServiceJni
#define _Included_com_drcom_drpalm_Tool_service_DrPushServiceJni
#ifdef __cplusplus
extern "C" {
#endif
#undef com_drcom_drpalm_Tool_service_DrPushServiceJni_TIME_FOR_CLEAN_JNI_LOG
#define com_drcom_drpalm_Tool_service_DrPushServiceJni_TIME_FOR_CLEAN_JNI_LOG 864000000LL
/*
 * Class:     com_drcom_drpalm_Tool_service_DrPushServiceJni
 * Method:    NativeInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_drcom_drpalm_Tool_service_DrPushServiceJni_NativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_drpalm_Tool_service_DrPushServiceJni
 * Method:    GetPushChallenge
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/drcom/drpalm/Tool/service/DrServiceJniCallback;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_drcom_drpalm_Tool_service_DrPushServiceJni_GetPushChallenge
  (JNIEnv *, jobject, jstring, jstring, jstring, jobject);

/*
 * Class:     com_drcom_drpalm_Tool_service_DrPushServiceJni
 * Method:    RegPushToken
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/drcom/drpalm/Tool/service/DrServiceJniCallback;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_drcom_drpalm_Tool_service_DrPushServiceJni_RegPushToken
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     com_drcom_drpalm_Tool_service_DrPushServiceJni
 * Method:    StartGetPushMessage
 * Signature: (Ljava/lang/String;Lcom/drcom/drpalm/Tool/service/DrServicePushJniCallback;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_drcom_drpalm_Tool_service_DrPushServiceJni_StartGetPushMessage
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_drcom_drpalm_Tool_service_DrPushServiceJni
 * Method:    StopUrlConnection
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_drcom_drpalm_Tool_service_DrPushServiceJni_StopUrlConnection
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_drcom_drpalm_Tool_service_DrPushServiceJni
 * Method:    GetFirstMacAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_drcom_drpalm_Tool_service_DrPushServiceJni_GetFirstMacAddress
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_drpalm_Tool_service_DrPushServiceJni
 * Method:    GetDeviceId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_drcom_drpalm_Tool_service_DrPushServiceJni_GetDeviceId
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_drpalm_Tool_service_DrPushServiceJni
 * Method:    GetTokenId
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_drcom_drpalm_Tool_service_DrPushServiceJni_GetTokenId
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
